In [1]:
!pip install --upgrade pandas

In [2]:
import pandas as pd
import numpy as np
pd.__version__

'1.3.3'

Esta linea sirve para mostrar solo dos cifras decimales:

In [3]:
pd.options.display.float_format = '{:.2f}'.format

Lo mismo con numpy dandole precisión 1

In [4]:
np.set_printoptions(precision=1)

Genero numeros aleatorios entre -1 y 1

In [5]:
np.random.randn()

0.5537305707133362

Genero una matriz de 2(filas) por 5(columnas)
Numeros positivos(rand)

In [6]:
np.random.rand(2, 5)

array([[0.1, 0.6, 0.9, 0.2, 0.5],
       [0.7, 0.3, 0.6, 0.4, 0.5]])

Almaceno ese dato en una variable y lo multiplico por 100

In [7]:
x1 = np.random.rand(2, 5)*100
x1

array([[70.8, 57.8, 37.4, 80.9, 20.8],
       [86.1, 13.5, 96.6, 20.5, 95.2]])

A esta nueva variable la covierto a numeros negativos

In [8]:
x2 = np.random.rand(2, 5)*-1
x2

array([[-0.1, -1. , -0.6, -0.1, -0.4],
       [-0.6, -0.3, -1. , -0.1, -0.4]])

### ***Concatenar matrices con numpy***

In [9]:
np.concatenate([x1, x2])

array([[ 7.1e+01,  5.8e+01,  3.7e+01,  8.1e+01,  2.1e+01],
       [ 8.6e+01,  1.3e+01,  9.7e+01,  2.1e+01,  9.5e+01],
       [-6.5e-02, -9.6e-01, -5.6e-01, -1.3e-01, -4.3e-01],
       [-5.5e-01, -3.1e-01, -9.6e-01, -5.5e-02, -3.8e-01]])

Veo la dimension de lo que he creado:

In [10]:
np.concatenate([x1, x2]).shape

(4, 5)

Concatenar en el eje de las columnas especificandolo:

In [11]:
np.concatenate([x1, x2], axis = 1)

array([[ 7.1e+01,  5.8e+01,  3.7e+01,  8.1e+01,  2.1e+01, -6.5e-02,
        -9.6e-01, -5.6e-01, -1.3e-01, -4.3e-01],
       [ 8.6e+01,  1.3e+01,  9.7e+01,  2.1e+01,  9.5e+01, -5.5e-01,
        -3.1e-01, -9.6e-01, -5.5e-02, -3.8e-01]])

Dimensiones del anterior:

In [12]:
np.concatenate([x1, x2], axis = 1).shape

(2, 10)

### ***Concatenar con Pandas***

Creo dos series:

In [13]:
s1 = pd.Series(x1[0], index = ['a','b','c','d','e'])
s1

a   70.75
b   57.82
c   37.38
d   80.94
e   20.78
dtype: float64

In [14]:
s2 = pd.Series(x2[0], index = ['c','d','e','f','g'])
s2

c   -0.06
d   -0.96
e   -0.56
f   -0.13
g   -0.43
dtype: float64

Concateno las dos series a lo largo de las filas:


In [15]:
pd.concat([s1, s2])

a   70.75
b   57.82
c   37.38
d   80.94
e   20.78
c   -0.06
d   -0.96
e   -0.56
f   -0.13
g   -0.43
dtype: float64

Concateno las dos series a lo largo de las columnas:

In [16]:
pd.concat([s1, s2], axis=1) # Aparece NaN porque esas letras no tienen valor  y respetan los indices

0     1
a 70.75   NaN
b 57.82   NaN
c 37.38 -0.06
d 80.94 -0.96
e 20.78 -0.56
f   NaN -0.13
g   NaN -0.43

Si quiero concatenar las series a los largo de las columnas pero sin respetar el indice:

In [17]:
s1.reset_index(drop=True) # reseteo su indice

0   70.75
1   57.82
2   37.38
3   80.94
4   20.78
dtype: float64

Obtengo ambas series concatenadas sin respetar el indice:

In [18]:
pd.concat([s1.reset_index(drop=True), s2.reset_index(drop=True)], axis=1)

0     1
0 70.75 -0.06
1 57.82 -0.96
2 37.38 -0.56
3 80.94 -0.13
4 20.78 -0.43

### ***Concatenar DataFrame***

In [19]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 9.94 1.85
1 6.56 6.61
2 3.50 3.11

In [21]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'], index = [2, 3, 4])
df2

a     b
2 -0.34 -0.42
3 -0.22 -0.88
4 -0.79 -0.45

Concateno los dos df:

In [22]:
pd.concat([df1, df2])

a     b
0  9.94  1.85
1  6.56  6.61
2  3.50  3.11
2 -0.34 -0.42
3 -0.22 -0.88
4 -0.79 -0.45

Los concateno a lo largo de columnas:

In [23]:
pd.concat([df1, df2], axis=1)

a    b     a     b
0 9.94 1.85   NaN   NaN
1 6.56 6.61   NaN   NaN
2 3.50 3.11 -0.34 -0.42
3  NaN  NaN -0.22 -0.88
4  NaN  NaN -0.79 -0.45

Si queremos hacer enfasis solo en el indice que se comparte(2):

In [24]:
pd.concat([df1, df2], axis=1, join='inner')

a    b     a     b
2 3.50 3.11 -0.34 -0.42

Concatenar dos df sin respetar sus indices:

In [25]:
pd.concat([df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis=1)

a    b     a     b
0 9.94 1.85 -0.34 -0.42
1 6.56 6.61 -0.22 -0.88
2 3.50 3.11 -0.79 -0.45

Funcion append para unir dos df

In [26]:
df1.append(df2)

a     b
0  9.94  1.85
1  6.56  6.61
2  3.50  3.11
2 -0.34 -0.42
3 -0.22 -0.88
4 -0.79 -0.45

Puedo hacer multiples append y se van a ir pegando uno abajo del otro:

In [27]:
df1.append(df2).append(df2)

a     b
0  9.94  1.85
1  6.56  6.61
2  3.50  3.11
2 -0.34 -0.42
3 -0.22 -0.88
4 -0.79 -0.45
2 -0.34 -0.42
3 -0.22 -0.88
4 -0.79 -0.45

Para pegar los append a lo largo de las columnas con la traspuesta, lo que hace es invertir las filas por las columnas

In [28]:
df1.T.append(df2.T).T

a    b     a     b
0 9.94 1.85   NaN   NaN
1 6.56 6.61   NaN   NaN
2 3.50 3.11 -0.34 -0.42
3  NaN  NaN -0.22 -0.88
4  NaN  NaN -0.79 -0.45