In [ ]:
10 + 3

13

In [ ]:
2 * 3 

6

In [ ]:
2 ** 3

8

In [ ]:
x = 12
x

12

In [ ]:
y = 15

In [ ]:
x + y

27

In [ ]:
'Hola mundo'

'Hola mundo'

In [ ]:
x = 'Hola'
y = 'Mundo'
x + y

'HolaMundo'

In [ ]:
x + ' ' + y

'Hola Mundo'

In [ ]:
[1, 2, 3, 5, 6]

[1, 2, 3, 5, 6]

In [ ]:
[1, 2, 3, 4] + [2, 3, 4]

[1, 2, 3, 4, 2, 3, 4]

In [ ]:
lista = [1, 2, 3, 4, 5]

In [ ]:
lista[0]

1

In [ ]:
lista[3]

4

In [ ]:
lista[-1]

5

In [ ]:
[1, 2, 3, 4] + [10]

[1, 2, 3, 4, 10]

np es un elemento que contiene una libreria para hacer analisis numérico:

In [ ]:
import numpy as np 

In [ ]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

Lo que hago es sumarle 10 a cada uno de los elementos de la lista:

In [ ]:
np.array([1, 2, 3, 4, 5]) + 10

array([11, 12, 13, 14, 15])

Para saber las dimensiones de nuestro vector:

In [ ]:
np.array([1, 2, 3, 4, 5]).shape 

(5,)

In [ ]:
np.array([[1, 2, 3, 4], [6, 7, 8, 9]])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

Nos muestra que tiene 2 dimensiones verticales y 4 dimensiones en la horizontal:

In [ ]:
np.array([[1, 2, 3, 4], [6, 7, 8, 9]]).shape

(2, 4)

Con esto obtengo con 0 la primer lista y con 2 me meto en esa lista y obtengo 3:

In [ ]:
np.array([[1, 2, 3, 4], [6, 7, 8, 9]])[0][2]

3

Esto me carga la libreria de pandas

In [ ]:
import pandas as pd 

Con esto me va a mostrar en que indice se encuetra cada numero de la lista:

In [ ]:
pd.Series([10, 9, 8, 7, 6]) 

0    10
1     9
2     8
3     7
4     6
dtype: int64

Guardo la lista anterior en una variable para ser mas comodo al requerir informacion:


In [ ]:
sr = pd.Series([10, 9, 8, 7, 6]) 
sr

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [ ]:
sr.values

array([10,  9,  8,  7,  6])

In [ ]:
sr.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
sr.shape

(5,)

In [ ]:
sr[3]

7

Obtengo los numeros de los indices 0, 4, 2 y esto respeta el orden en que lo pongo:

In [ ]:
sr[[0,4,2]]

0    10
4     6
2     8
dtype: int64

Obtengo un sistema de indices con letras:

In [ ]:
sr = pd.Series([10, 9, 8, 7, 6], index = ['a','b','c','d','e',]) 
sr

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [ ]:
sr ['c']

8

In [ ]:
sr [['c','d','e']]

c    8
d    7
e    6
dtype: int64

In [ ]:
sr['b':'e'] # aqui obtengo los datos de b a e

b    9
c    8
d    7
e    6
dtype: int64

In [ ]:
dict_data = {'CO':100, 'MX':200, 'AR':300}
dict_data

{'AR': 300, 'CO': 100, 'MX': 200}

In [ ]:
dict_data.keys() # obtengo solo llaves

dict_keys(['CO', 'MX', 'AR'])

In [ ]:
dict_data['MX'] # obtengo el contenido de esa llave

200

In [ ]:
pd.Series(dict_data)

CO    100
MX    200
AR    300
dtype: int64

Creamos una serie basada en nuestro diccionario en donde el indice esta definido por las llaves de nuestro diccionario y los valores de nuestra serie.

Aparece NaN porque cambie el nombre de la llave de AR por PE

In [ ]:
pd.Series(dict_data, index = ['CO','MX','PE']) 

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [ ]:
import numpy as np

In [ ]:
np.nan+10

nan

In [ ]:
np.nan*10


nan

In [ ]:
sr = pd.Series(dict_data, index = ['CO','MX','PE'])
sr

CO    100.0
MX    200.0
PE      NaN
dtype: float64

Me marca donde está mi variable o valor nulo:

In [ ]:
sr.isnull() 

CO    False
MX    False
PE     True
dtype: bool

Me marca las variables no nulas:

In [ ]:
sr.notnull()  

CO     True
MX     True
PE    False
dtype: bool